---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: "dockeryaodi/hello-world:latest"
        name: hello-world
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30440
  selector:
    app: hello-world

Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
